// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.Company;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Mono.FireControl.UI;
[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;
    // Forge-Change-Start: weapon preset UI callbacks.
    public Action<int, string>? OnPresetNameChanged;
    public Action<int, string, List<string>>? OnPresetSaveRequested;
    // Forge-Change-End

    public readonly Dictionary<NetEntity, Button> WeaponsList = new();

    // Dictionary to store weapon name to entity mapping for easier filtering
    private readonly Dictionary<string, NetEntity> _weaponNameToEntity = new();

    // Dictionary to store weapon entity to type mapping
    private readonly Dictionary<NetEntity, ShipGunType> _weaponTypes = new();

    private FireControlConsoleBoundInterfaceState? _currentState;
    // Forge-Change: max weapons that can be selected/fired at once (from server MaxWeapons).
    private int _maxActiveWeapons = int.MaxValue;

    private LineEdit[] _presetNameEdits = default!;
    private Button[] _presetLoadButtons = default!;

    // Forge-Change-Start: collapsible side panels with dynamic window width.
    private bool _controlsPanelExpanded = true;
    private bool _weaponsPanelExpanded = true;

    private const float SidePanelBlockWidth = 305f;
    private const float WindowChromeWidth = 42f;
    private const float DefaultWindowHeight = 800f;
    private const float MinimumWindowHeight = 700f;

    private enum PanelSide
    {
        Left,
        Right,
    }
    // Forge-Change-End

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _presetNameEdits = [Preset1NameEdit, Preset2NameEdit, Preset3NameEdit];
        _presetLoadButtons = [Preset1LoadButton, Preset2LoadButton, Preset3LoadButton];

        ControlsPanelToggle.OnPressed += _ => ToggleControlsPanel();
        WeaponsPanelToggle.OnPressed += _ => ToggleWeaponsPanel();
        InitializeRadarLayout();
        UpdateControlsPanelState();
        UpdateWeaponsPanelState();

        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        ShowIFFCheckbox.OnToggled += args => NavRadar.ShowIFF = args.Pressed; // Forge-Change
        SelectAllButton.OnPressed += SelectAllWeapons;
        UnselectAllButton.OnPressed += UnselectAllWeapons;
        SelectBallisticButton.OnPressed += SelectBallisticWeapons;
        SelectEnergyButton.OnPressed += SelectEnergyWeapons;
        SelectMissileButton.OnPressed += SelectMissileWeapons;
        IffSearchCriteria.OnTextChanged += args => OnIffSearchChanged(args.Text);

        InitializePresetControls();
        ApplyWindowLayout(initial: true);
    }

    // Forge-Change-Start: radar fill + edge toggle buttons that stay visible when window narrows.
    private void InitializeRadarLayout()
    {
        LayoutContainer.SetAnchorPreset(NavRadar, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorAndMarginPreset(ControlsPanelToggle, LayoutContainer.LayoutPreset.CenterLeft);
        LayoutContainer.SetAnchorAndMarginPreset(WeaponsPanelToggle, LayoutContainer.LayoutPreset.CenterRight);

        ControlsPanelToggle.MouseFilter = MouseFilterMode.Stop;
        WeaponsPanelToggle.MouseFilter = MouseFilterMode.Stop;

        // Draw toggles above the radar surface.
        ControlsPanelToggle.SetPositionInParent(RadarHost.ChildCount - 1);
        WeaponsPanelToggle.SetPositionInParent(RadarHost.ChildCount - 1);
    }

    private void ToggleControlsPanel()
    {
        _controlsPanelExpanded = !_controlsPanelExpanded;
        UpdateControlsPanelState();
        ApplyWindowLayout(resizedSide: PanelSide.Left);
    }

    private void ToggleWeaponsPanel()
    {
        _weaponsPanelExpanded = !_weaponsPanelExpanded;
        UpdateWeaponsPanelState();
        ApplyWindowLayout(resizedSide: PanelSide.Right);
    }

    private float GetRadarDisplayWidth()
    {
        var scaledSize = (MapGridControl.UIDisplayRadius + 4) * 2 * UIScale;
        return MathF.Max(NavRadar.Width, scaledSize);
    }

    private float ComputeContentWidth()
    {
        var width = GetRadarDisplayWidth();

        if (_controlsPanelExpanded)
            width += SidePanelBlockWidth;

        if (_weaponsPanelExpanded)
            width += SidePanelBlockWidth;

        return width;
    }

    private void ApplyWindowLayout(bool initial = false, PanelSide? resizedSide = null)
    {
        var targetWidth = ComputeContentWidth() + WindowChromeWidth;
        MinSize = new Vector2(targetWidth, MinimumWindowHeight);

        if (initial)
        {
            SetSize = new Vector2(targetWidth, DefaultWindowHeight);
            return;
        }

        var widthDelta = targetWidth - Width;

        if (resizedSide == PanelSide.Left && Math.Abs(widthDelta) > 0.1f)
            LayoutContainer.SetPosition(this, Position + new Vector2(-widthDelta, 0));

        SetSize = new Vector2(targetWidth, Height);
    }
    // Forge-Change-End

    private void UpdateControlsPanelState()
    {
        ControlsPanel.Visible = _controlsPanelExpanded;
        ControlsPanelToggle.Text = _controlsPanelExpanded ? "«" : "»";
        ControlsPanelToggle.ToolTip = Loc.GetString(_controlsPanelExpanded
            ? "gunnery-panel-collapse-controls"
            : "gunnery-panel-expand-controls");
    }

    private void UpdateWeaponsPanelState()
    {
        WeaponsPanel.Visible = _weaponsPanelExpanded;
        WeaponsPanelToggle.Text = _weaponsPanelExpanded ? "»" : "«";
        WeaponsPanelToggle.ToolTip = Loc.GetString(_weaponsPanelExpanded
            ? "gunnery-panel-collapse-weapons"
            : "gunnery-panel-expand-weapons");
    }

    // Forge-Change-Start: three renameable weapon preset slots per console.
    private void InitializePresetControls()
    {
        for (var i = 0; i < FireControlConsoleComponent.WeaponPresetCount; i++)
        {
            var index = i;
            _presetNameEdits[i].Text = GetPresetDisplayName(i);
            _presetNameEdits[i].OnTextEntered += _ => OnPresetNameCommitted(index);
            _presetLoadButtons[i].OnPressed += _ => ApplyPreset(index);
        }

        SavePresetButton.OnPressed += _ => SaveActivePreset();
        // OptionButton requires explicit SelectId on item pick.
        PresetSaveTarget.OnItemSelected += args => PresetSaveTarget.SelectId(args.Id);
        RebuildSaveTargetOptions();
    }

    private string GetDefaultPresetName(int index)
    {
        return Loc.GetString("gunnery-preset-default-name", ("number", index + 1));
    }

    private string GetPresetDisplayName(int index)
    {
        if (_currentState?.WeaponPresets != null
            && index < _currentState.WeaponPresets.Length
            && !string.IsNullOrWhiteSpace(_currentState.WeaponPresets[index].Name))
        {
            return _currentState.WeaponPresets[index].Name;
        }

        return GetDefaultPresetName(index);
    }

    private void SyncPresetNamesFromState()
    {
        var namesChanged = false;

        for (var i = 0; i < FireControlConsoleComponent.WeaponPresetCount; i++)
        {
            if (_presetNameEdits[i].HasKeyboardFocus())
                continue;

            var displayName = GetPresetDisplayName(i);
            if (_presetNameEdits[i].Text == displayName)
                continue;

            _presetNameEdits[i].Text = displayName;
            namesChanged = true;
        }

        if (namesChanged)
            RebuildSaveTargetOptions();
    }

    private void RebuildSaveTargetOptions()
    {
        var selected = PresetSaveTarget.SelectedId;
        if (selected < 0)
            selected = 0;

        PresetSaveTarget.Clear();

        for (var i = 0; i < FireControlConsoleComponent.WeaponPresetCount; i++)
        {
            var name = _presetNameEdits[i].Text.Trim();
            if (string.IsNullOrWhiteSpace(name))
                name = GetDefaultPresetName(i);

            PresetSaveTarget.AddItem(Loc.GetString("gunnery-preset-save-target", ("name", name)), i);
        }

        if (selected >= 0 && selected < FireControlConsoleComponent.WeaponPresetCount)
            PresetSaveTarget.SelectId(selected);
        else
            PresetSaveTarget.SelectId(0);
    }

    private void OnPresetNameCommitted(int index)
    {
        var name = _presetNameEdits[index].Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            name = GetDefaultPresetName(index);

        _presetNameEdits[index].Text = name;
        OnPresetNameChanged?.Invoke(index, name);
        RebuildSaveTargetOptions();
    }

    private void SaveActivePreset()
    {
        var index = PresetSaveTarget.SelectedId;
        if (index < 0 || index >= FireControlConsoleComponent.WeaponPresetCount)
            return;

        var name = _presetNameEdits[index].Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            name = GetDefaultPresetName(index);

        _presetNameEdits[index].Text = name;
        var weaponNames = GetSelectedWeaponNames();
        OnPresetSaveRequested?.Invoke(index, name, weaponNames);

        ShowPresetStatus(Loc.GetString("gunnery-preset-saved", ("name", name), ("count", weaponNames.Count)));
    }

    private void ApplyPreset(int index)
    {
        if (index < 0 || index >= FireControlConsoleComponent.WeaponPresetCount)
            return;

        var name = _presetNameEdits[index].Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            name = GetDefaultPresetName(index);

        if (_currentState?.WeaponPresets == null
            || index >= _currentState.WeaponPresets.Length
            || _currentState.WeaponPresets[index].WeaponNames.Length == 0)
        {
            ShowPresetStatus(Loc.GetString("gunnery-preset-empty", ("name", name)), warning: true);
            return;
        }

        var matched = MatchWeaponsByName(_currentState.WeaponPresets[index].WeaponNames);
        PressWeaponsUpToLimit(matched);
        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();

        ShowPresetStatus(Loc.GetString("gunnery-preset-applied", ("name", name), ("count", matched.Count())));
    }

    private List<string> GetSelectedWeaponNames()
    {
        var names = new List<string>();

        foreach (var (entity, button) in WeaponsList)
        {
            if (!button.Pressed)
                continue;

            var entry = _currentState?.FireControllables?.FirstOrDefault(c => c.NetEntity == entity);
            if (entry.HasValue)
                names.Add(entry.Value.Name);
        }

        return names;
    }

    private IEnumerable<NetEntity> MatchWeaponsByName(IReadOnlyList<string> weaponNames)
    {
        if (_currentState?.FireControllables == null)
            yield break;

        var used = new HashSet<NetEntity>();

        foreach (var weaponName in weaponNames)
        {
            foreach (var controllable in _currentState.FireControllables)
            {
                if (controllable.Name != weaponName || used.Contains(controllable.NetEntity))
                    continue;

                used.Add(controllable.NetEntity);
                yield return controllable.NetEntity;
                break;
            }
        }
    }

    private void ShowPresetStatus(string message, bool warning = false)
    {
        PresetStatusLabel.Text = message;
        PresetStatusLabel.FontColorOverride = warning ? Color.OrangeRed : Color.LightGreen;

        Timer.Spawn(TimeSpan.FromSeconds(2.5), () =>
        {
            if (!PresetStatusLabel.Disposed)
                PresetStatusLabel.Text = string.Empty;
        });
    }
    // Forge-Change-End

    private void OnIffSearchChanged(string text)
    {
        text = text.Trim();

        NavRadar.IFFFilter = text.Length == 0
            ? null
            : (entity, grid, iff, hideLabel, name) =>
            {
                if (name.Contains(text, StringComparison.OrdinalIgnoreCase))
                    return true;
                if (hideLabel)
                    return false;

                if (_entityManager.TryGetComponent<CompanyComponent>(entity, out var companyComp) &&
                    !string.IsNullOrEmpty(companyComp.CompanyName))
                {
                    if (companyComp.CompanyName.Id.Contains(text, StringComparison.OrdinalIgnoreCase))
                        return true;

                    if (_prototypeManager.TryIndex(companyComp.CompanyName, out var prototype) &&
                        prototype.Name.Contains(text, StringComparison.OrdinalIgnoreCase))
                        return true;
                }

                return false;
            };
    }

    // Forge-Change-Start: client-side enforcement of MaxWeapons selection cap.
    private int GetSelectedWeaponCount()
    {
        return WeaponsList.Values.Count(button => button.Pressed);
    }

    private bool TryToggleWeaponSelection(Button button)
    {
        if (!button.Pressed)
            return true;

        if (_maxActiveWeapons <= 0 || GetSelectedWeaponCount() <= _maxActiveWeapons)
            return true;

        button.Pressed = false;
        return false;
    }

    private void PressWeaponsUpToLimit(IEnumerable<NetEntity> weaponEntities)
    {
        foreach (var button in WeaponsList.Values)
            button.Pressed = false;

        var selected = 0;
        foreach (var weaponEntity in weaponEntities)
        {
            if (_maxActiveWeapons > 0 && selected >= _maxActiveWeapons)
                break;

            if (!WeaponsList.TryGetValue(weaponEntity, out var button))
                continue;

            button.Pressed = true;
            selected++;
        }
    }

    private void SelectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        PressWeaponsUpToLimit(WeaponsList.Keys);

        OnWeaponSelectionChanged?.Invoke();

        UpdateAllWeaponButtonTexts();
    }

    private void UnselectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        OnWeaponSelectionChanged?.Invoke();

        UpdateAllWeaponButtonTexts();
    }

    private void SelectBallisticWeapons(BaseButton.ButtonEventArgs args)
    {
        var ballistic = WeaponsList.Keys
            .Where(weaponEntity =>
                _weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Ballistic);

        PressWeaponsUpToLimit(ballistic);

        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();
    }

    private void SelectEnergyWeapons(BaseButton.ButtonEventArgs args)
    {
        var energy = WeaponsList.Keys
            .Where(weaponEntity =>
                _weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Energy);

        PressWeaponsUpToLimit(energy);

        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();
    }

    private void SelectMissileWeapons(BaseButton.ButtonEventArgs args)
    {
        var missiles = WeaponsList.Keys
            .Where(weaponEntity =>
                _weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Missile);

        PressWeaponsUpToLimit(missiles);

        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();
    }

    /// <summary>
    /// Updates the text of a weapon button based on its selection state and manual reload status.
    /// </summary>
    private void UpdateWeaponButtonText(Button button, FireControllableEntry controllable)
    {
        if (button.Pressed && controllable.HasManualReload && controllable.AmmoCount.HasValue)
        {
            button.Text = Loc.GetString("gunnery-gun-select-ammo", ("name", controllable.Name), ("ammo", controllable.AmmoCount.Value));
        }
        else
        {
            button.Text = Loc.GetString("gunnery-gun-select", ("name", controllable.Name));
        }

        UpdateWeaponButtonVisualState(button, controllable);
    }

    // Forge-Change: green/red modulate override — toggle pressed pseudo-class looks inactive otherwise.
    /// <summary>
    /// Toggle buttons use a dark pressed pseudo-class; override modulate so selected weapons read clearly.
    /// </summary>
    private static void UpdateWeaponButtonVisualState(Button button, FireControllableEntry controllable)
    {
        if (!button.Pressed)
        {
            button.ModulateSelfOverride = null;
            return;
        }

        if (controllable.HasManualReload && controllable.AmmoCount is 0)
            button.ModulateSelfOverride = Color.Red;
        else
            button.ModulateSelfOverride = StyleNano.ButtonColorGoodDefault;
    }

    /// <summary>
    /// Updates all weapon button texts based on current selection state.
    /// </summary>
    private void UpdateAllWeaponButtonTexts()
    {
        foreach (var (netEntity, button) in WeaponsList)
        {
            var controllable = _currentState?.FireControllables?.FirstOrDefault(c => c.NetEntity == netEntity);

            if (controllable.HasValue)
            {
                UpdateWeaponButtonText(button, controllable.Value);
            }
        }
    }

    /// <summary>
    /// Forge-Change: feed the shield bar with the grid the console is mounted on. Called by the BUI when the
    /// console's transform/grid context is known.
    /// </summary>
    public void SetShuttle(EntityUid? grid)
    {
        ShieldBar.SetGrid(grid);
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        _currentState = state;
        _maxActiveWeapons = state.MaxActiveWeapons; // Forge-Change
        NavRadar.UpdateState(state.NavState);

        // Forge-Change: bar reads the networked emitter directly; only sync visibility here.
        ShieldPanel.Visible = ShieldBar.HasShield;

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        UpdateWeaponsList(state);
        EnforceActiveWeaponLimit();
        SyncPresetNamesFromState();

        UpdateAllWeaponButtonTexts();

        // Update the category buttons state based on whether weapons of that type are available
        bool hasBallisticWeapons = false;
        bool hasEnergyWeapons = false;
        bool hasMissileWeapons = false;

        foreach (var kvp in _weaponTypes)
        {
            var type = kvp.Value;

            if (type == ShipGunType.Ballistic)
                hasBallisticWeapons = true;
            else if (type == ShipGunType.Energy)
                hasEnergyWeapons = true;
            else if (type == ShipGunType.Missile)
                hasMissileWeapons = true;

            if (hasBallisticWeapons && hasEnergyWeapons && hasMissileWeapons)
                break;
        }

        SelectBallisticButton.Disabled = !hasBallisticWeapons;
        SelectEnergyButton.Disabled = !hasEnergyWeapons;
        SelectMissileButton.Disabled = !hasMissileWeapons;
    }

    // Forge-Change-Start: keep shield panel visibility in sync with the live emitter component.
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ShieldPanel.Visible = ShieldBar.HasShield;
    }
    // Forge-Change-End

    private void UpdateWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        if (state.FireControllables == null)
        {
            WeaponsList.Clear();
            ControllablesBox.DisposeAllChildren();
            _weaponNameToEntity.Clear();
            _weaponTypes.Clear();
            return;
        }

        var toRemove = new HashSet<NetEntity>(WeaponsList.Keys);
        _weaponNameToEntity.Clear();
        _weaponTypes.Clear();

        foreach (var controllable in state.FireControllables)
        {
            // Store the weapon name and entity for filtering
            _weaponNameToEntity[controllable.Name] = controllable.NetEntity;

            // Store the weapon type if available
            var entity = _entityManager.GetEntity(controllable.NetEntity);
            if (_entityManager.TryGetComponent<ShipGunTypeComponent>(entity, out var typeComp))
            {
                _weaponTypes[controllable.NetEntity] = typeComp.Type;
            }

            if (WeaponsList.TryGetValue(controllable.NetEntity, out var existingButton))
            {
                toRemove.Remove(controllable.NetEntity);
                UpdateWeaponButtonText(existingButton, controllable);
            }
            else
            {
                // Forge-Change: ButtonSquare only (no OpenRight) + explicit selected color.
                var button = new Button
                {
                    ToggleMode = true,
                    Text = controllable.Name,
                    StyleClasses = { "ButtonSquare" },
                    TextAlign = Label.AlignMode.Left,
                    HorizontalExpand = true,
                    Margin = new Thickness(2, 1)
                };

                button.OnToggled += _ =>
                {
                    if (!TryToggleWeaponSelection(button))
                        return;

                    OnWeaponSelectionChanged?.Invoke();
                    UpdateAllWeaponButtonTexts();
                };

                ControllablesBox.AddChild(button);
                WeaponsList.Add(controllable.NetEntity, button);

                UpdateWeaponButtonText(button, controllable);
            }
        }

        foreach (var entity in toRemove)
        {
            if (WeaponsList.TryGetValue(entity, out var button))
            {
                ControllablesBox.RemoveChild(button);
                WeaponsList.Remove(entity);
            }
        }

        SelectAllButton.Disabled = WeaponsList.Count == 0;
        UnselectAllButton.Disabled = WeaponsList.Count == 0;
    }

    /// <summary>
    /// Trims selection when the active firing limit drops below the current selection count.
    /// </summary>
    private void EnforceActiveWeaponLimit()
    {
        if (_maxActiveWeapons <= 0)
            return;

        var selected = WeaponsList.Where(kvp => kvp.Value.Pressed).Select(kvp => kvp.Key).ToList();
        if (selected.Count <= _maxActiveWeapons)
            return;

        PressWeaponsUpToLimit(selected);
    }
    // Forge-Change-End
}
